// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABt0OsW4y_SwozxOmnNpDsTePvy8BjUPk',
    appId: '1:533598873146:web:dacece2f120c24dea4b703',
    messagingSenderId: '533598873146',
    projectId: 'berangkatin-46d72',
    authDomain: 'berangkatin-46d72.firebaseapp.com',
    storageBucket: 'berangkatin-46d72.firebasestorage.app',
    measurementId: 'G-GSPJZVTPSS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAChxNZPSNL5NxwY5JRRyY28Nw2y5PLYYs',
    appId: '1:533598873146:android:1f569a8e7b822130a4b703',
    messagingSenderId: '533598873146',
    projectId: 'berangkatin-46d72',
    storageBucket: 'berangkatin-46d72.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-V3KsYdKRItwblzSUtBFibLhpybajIxo',
    appId: '1:533598873146:ios:245e8c2647f0445ca4b703',
    messagingSenderId: '533598873146',
    projectId: 'berangkatin-46d72',
    storageBucket: 'berangkatin-46d72.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-V3KsYdKRItwblzSUtBFibLhpybajIxo',
    appId: '1:533598873146:ios:245e8c2647f0445ca4b703',
    messagingSenderId: '533598873146',
    projectId: 'berangkatin-46d72',
    storageBucket: 'berangkatin-46d72.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );
}
